{
    "name": "Instance Creator for Almik",
    "summary": """
    Instance creator for almik. This is the app.
    """,
    "author": "Vauxoo",
    "website": "https://www.vauxoo.com",
    "license": "OPL-1",
    "category": "Installer",
    "version": "16.0.1.1.6",
    "depends": [
        "account_budget",
        "account_reports_cash_basis",
        "addenda_dunosusa",
        "addenda_envases",
        "addenda_sanmina",
        "board",
        "crm",
        "documents",
        "fleet",
        "helpdesk",
        "hr_expense",
        "industry_fsm",
        "internal_transfer_with_agreed_amount",
        "l10n_mx_edi_cancellation",
        "l10n_mx_edi_extended_40",
        "l10n_mx_edi_fiscal_legend",
        "l10n_mx_edi_landing",
        "l10n_mx_edi_partner_defaults",
        "l10n_mx_edi_stock_advanced",
        "l10n_mx_edi_stock_extended_40",
        "l10n_mx_edi_payment_split",
        "maintenance",
        "mrp_subcontracting",
        "mrp_workorder",
        "note",
        "product_margin",
        "product_supplierinfo_for_customer",
        "sale_margin",
        "stock_barcode",
        "stock_mts_mto_rule",
        "stock_no_negative",
        "stock_quantity_history_location",
        "stock_tracking_fields",
        "survey",
        "website_google_map",
        "website_slides",
    ],
    "data": [
        # data
        "data/cfdi.xml",
        "data/report_paperformat_data.xml",
        "data/res_company_data.xml",
        "data/res_partner_data.xml",
        # security
        "security/ir_module_category_security.xml",
        "security/res_groups_security.xml",
        # reports
        "reports/layout_templates.xml",
        "reports/mrp_production_templates.xml",
        "reports/purchase_report_templates.xml",
        "reports/remission_report.xml",
        "reports/report_invoice_document.xml",
        "reports/report_payment_receipt_document.xml",
        "reports/sale_report_templates.xml",
        # views
        "views/account_move_line_views.xml",
        "views/account_move_views.xml",
        "views/crm_lead_views.xml",
        "views/purchase_order_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/sale_order_line_views.xml",
        "views/stock_picking_views.xml",
        "views/uom_uom_views.xml",
        "wizard/crm_lead_lost_views.xml",
    ],
    "demo": [
        "demo/product_category_demo.xml",
        "demo/product_product_demo.xml",
        "demo/res_partner_demo.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
}
